### ISSUE TITLE
Keyboard bindings problems

### ISSUE THREAD

**Issue by rbtylee** [Obsidian-StudiosInc/clipboard#1]
I am using [nicos enlightenment ppa](https://launchpad.net/~niko2040/+archive/ubuntu/e19) and the clipboard module prior to your last commit. (Ubuntu 16.04 base)

Looking at keyboard binding issues in moksha's version of the clipboard lead me to examine how this e22 version acts.  A key press bound to Show History doesn't seem to work at all. Key presses bound to Show Settings or Clear History cause a seg fault.

The issue with Show History I did not look for the cause. Nothing out of the ordinary in stdout or stderror.

I have backtraces on the other two issues:

alt s bound to show settings:

```
Thread 1 "enlightenment" received signal SIGSEGV, Segmentation fault.
0x0812e4fc in e_object_del ()
(gdb) bt
#0  0x0812e4fc in e_object_del ()
#1  0xb176f1fc in _clipboard_popup_free (inst=0xbffac208)
    at ../src/e_mod_main.c:272
#2  0xb17709f4 in _clipboard_config_show (d1=0xbffac208, d2=0x0)
    at ../src/e_mod_main.c:743
#3  0xb1770a1f in _cb_config_show (data=0xbffac208, m=0x0, mi=0x0)
    at ../src/e_mod_main.c:751
#4  0xb176fd68 in _cb_action_switch (o=0x83737f8, params=0x8388c20 "settings", 
    data=0xbffac208, evas=0xb6deab32 <_XEventsQueued+114>, 
    obj=0xb6deaac7 <_XEventsQueued+7>, event=0xb6dd8546)
    at ../src/e_mod_main.c:496
#5  0x08088800 in e_bindings_key_down_event_handle ()
#6  0x080a2462 in ?? ()
#7  0xb75adbde in _ecore_call_handler_cb (event=<optimized out>, 
    type=<optimized out>, data=<optimized out>, func=<optimized out>)
    at lib/ecore/ecore_private.h:325
#8  _ecore_event_call () at lib/ecore/ecore_events.c:518
#9  0xb75b5aa4 in _ecore_main_loop_iterate_internal (
    once_only=once_only@entry=0) at lib/ecore/ecore_main.c:2399
#10 0xb75b5ed7 in ecore_main_loop_begin () at lib/ecore/ecore_main.c:1299
#11 0x0807ad4b in main ()
```

alt c bound to clear history:

```
Thread 1 "enlightenment" received signal SIGSEGV, Segmentation fault.
0xb176f1e4 in _clipboard_popup_free (inst=0x0) at ../src/e_mod_main.c:272
272	  E_FREE_FUNC(inst->popup, e_object_del);
(gdb) bt
#0  0xb176f1e4 in _clipboard_popup_free (inst=0x0) at ../src/e_mod_main.c:272
#1  0xb176fbff in _cb_clear_history (d1=0x0, d2=0x0) at ../src/e_mod_main.c:445
#2  0xb176fda1 in _cb_action_switch (o=0x836a088, params=0x837eac0 "clear", 
    data=0xbffac208, evas=0xb6deab32 <_XEventsQueued+114>, 
    obj=0xb6deaac7 <_XEventsQueued+7>, event=0xb6dd8546)
    at ../src/e_mod_main.c:499
#3  0x08088800 in e_bindings_key_down_event_handle ()
#4  0x080a2462 in ?? ()
#5  0xb75adbde in _ecore_call_handler_cb (event=<optimized out>, 
    type=<optimized out>, data=<optimized out>, func=<optimized out>)
    at lib/ecore/ecore_private.h:325
#6  _ecore_event_call () at lib/ecore/ecore_events.c:518
#7  0xb75b5aa4 in _ecore_main_loop_iterate_internal (
    once_only=once_only@entry=0) at lib/ecore/ecore_main.c:2399
#8  0xb75b5ed7 in ecore_main_loop_begin () at lib/ecore/ecore_main.c:1299
#9  0x0807ad4b in main ()
```

Reporting this before I neglect to and forget it. I could probably fix it but lack time to look further now.

**Comment by wltjr** [comment]
I have not done anything with the key bindings myself. I am not sure I was even aware of them. I will need to test that out and see about a fix. Thanks for reporting!
